require 'Items/ProceduralDistributions'

table.insert(ProceduralDistributions["list"]["FirearmWeapons_Late"].items, "PZCrossbows.HandCrossBow")
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Late"].items, 1.5 * SandboxVars.PZCrossbows.HandCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Late"].items, "PZCrossbows.CompoundCrossBow")
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Late"].items, 3 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Late"].items, "PZCrossbows.ImprovedCrossBow")
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Late"].items, 2 * SandboxVars.PZCrossbows.ImprovedCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Late"].items, "PZCrossbows.WoodBolt")
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Late"].items, 4 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)

table.insert(ProceduralDistributions["list"]["FirearmWeapons_Mid"].items, "PZCrossbows.ImprovedCrossBow")
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Mid"].items, 1 * SandboxVars.PZCrossbows.ImprovedCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Mid"].items, "PZCrossbows.Crossbow")
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Mid"].items, 2 * SandboxVars.PZCrossbows.CrudeCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Mid"].items, "PZCrossbows.CompoundCrossBow")
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Mid"].items, 2 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Mid"].items, "PZCrossbows.WoodBolt")
table.insert(ProceduralDistributions["list"]["FirearmWeapons_Mid"].items, 4 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)

table.insert(ProceduralDistributions["list"]["FirearmWeapons"].items, "PZCrossbows.CompoundCrossBow")
table.insert(ProceduralDistributions["list"]["FirearmWeapons"].items, 3 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["FirearmWeapons"].items, "PZCrossbows.WoodBolt")
table.insert(ProceduralDistributions["list"]["FirearmWeapons"].items, 4 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)

table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, "PZCrossbows.CompoundCrossBow")
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, 3 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, "PZCrossbows.CompoundCrossBow")
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, 0.12 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["Hunter"].items, "PZCrossbows.CompoundCrossBow")
table.insert(ProceduralDistributions["list"]["Hunter"].items, 2 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["Hunter"].items, "PZCrossbows.ImprovedCrossBow")
table.insert(ProceduralDistributions["list"]["Hunter"].items, 1.5 * SandboxVars.PZCrossbows.ImprovedCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["CampingLockers"].items, "PZCrossbows.CompoundCrossBow")
table.insert(ProceduralDistributions["list"]["CampingLockers"].items, 0.1 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, "PZCrossbows.CompoundCrossBow")
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, 0.1 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["GunStoreGuns"].items, "PZCrossbows.CompoundCrossBow")
table.insert(ProceduralDistributions["list"]["GunStoreGuns"].items, 6 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
table.insert(ProceduralDistributions["list"]["GunStoreAmmunition"].items, "PZCrossbows.WoodBolt")
table.insert(ProceduralDistributions["list"]["GunStoreAmmunition"].items, 6 * SandboxVars.PZCrossbows.CompoundCrossbowSpawnMult)
