require 'Foraging/forageSystem'
Events.onAddForageDefs.Add(function()
local itemsToAdd = {
	CompoundCrossbow ={
	type = "PZCrossbows.CompoundCrossBow",
		minCount=1,
		maxCount=1,
		xp=20,
		skill=4,
		categories = { "Junk" },
		zones = {
				BirchForest		= 2,
				PHForest		= 2,
				PRForest		= 2,
				DeepForest		= 3,
				FarmLand    	= 5,
				ForagingNav 	= 3,
				Forest      	= 5,
				OrganicForest	= 3,
				TownZone    	= 5,
				TrailerPark 	= 2,
				Vegitation  	= 3,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	ImprovedCrossbow ={
	type = "PZCrossbows.ImprovedCrossBow",
		minCount=1,
		maxCount=1,
		xp=20,
		skill=4,
		categories = { "Junk" },
		zones = {
				BirchForest		= 1,
				PHForest		= 1,
				PRForest		= 1,
				DeepForest		= 1,
				FarmLand    	= 2,
				ForagingNav 	= 1,
				Forest      	= 1,
				OrganicForest	= 1,
				TownZone    	= 2,
				TrailerPark 	= 2,
				Vegitation  	= 2,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	CrudeCrossbow ={
	type = "PZCrossbows.Crossbow",
		minCount=1,
		maxCount=1,
		xp=20,
		skill=4,
		categories = { "Junk" },
		zones = {
				BirchForest		= 3,
				PHForest		= 3,
				PRForest		= 3,
				DeepForest		= 3,
				FarmLand    	= 3,
				ForagingNav 	= 3,
				Forest      	= 3,
				OrganicForest	= 3,
				TownZone    	= 5,
				TrailerPark 	= 5,
				Vegitation  	= 3,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	HandCrossbow ={
	type = "PZCrossbows.HandCrossBow",
		minCount=1,
		maxCount=1,
		xp=20,
		skill=4,
		categories = { "Junk" },
		zones = {
				BirchForest		= 2,
				PHForest		= 2,
				PRForest		= 2,
				DeepForest		= 2,
				FarmLand    	= 2,
				ForagingNav 	= 2,
				Forest      	= 2,
				OrganicForest	= 2,
				TownZone    	= 2,
				TrailerPark 	= 2,
				Vegitation  	= 2,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	ShortBolts ={
	type = "PZCrossbows.ShortWoodBolt",
		minCount=1,
		maxCount=5,
		xp=5,
		skill=4,
		categories = { "Ammunition" },
		zones = {
				BirchForest		= 3,
				PHForest		= 3,
				PRForest		= 3,
				DeepForest		= 3,
				FarmLand    	= 3,
				ForagingNav 	= 3,
				Forest      	= 3,
				OrganicForest	= 3,
				TownZone    	= 3,
				TrailerPark 	= 3,
				Vegitation  	= 3,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	ShortBrokenBolts ={
	type = "PZCrossbows.BrokenShortBolt",
		minCount=1,
		maxCount=3,
		xp=5,
		skill=4,
		categories = { "Junk" },
		zones = {
				BirchForest		= 5,
				PHForest		= 5,
				PRForest		= 5,
				DeepForest		= 5,
				FarmLand    	= 5,
				ForagingNav 	= 5,
				Forest      	= 5,
				OrganicForest	= 5,
				TownZone    	= 5,
				TrailerPark 	= 5,
				Vegitation  	= 5,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	ShortBoltShaft ={
	type = "PZCrossbows.ShortWoodBoltShaft",
		minCount=1,
		maxCount=5,
		xp=5,
		skill=4,
		categories = { "Junk" },
		zones = {
				BirchForest		= 1,
				PHForest		= 1,
				PRForest		= 1,
				DeepForest		= 1,
				FarmLand    	= 1,
				ForagingNav 	= 1,
				Forest      	= 1,
				OrganicForest	= 1,
				TownZone    	= 1,
				TrailerPark 	= 1,
				Vegitation  	= 1,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	Bolts ={
	type = "PZCrossbows.WoodBolt",
		minCount=1,
		maxCount=3,
		xp=5,
		skill=4,
		categories = { "Ammunition" },
		zones = {
				BirchForest		= 3,
				PHForest		= 3,
				PRForest		= 3,
				DeepForest		= 3,
				FarmLand    	= 3,
				ForagingNav 	= 3,
				Forest      	= 3,
				OrganicForest	= 3,
				TownZone    	= 3,
				TrailerPark 	= 3,
				Vegitation  	= 3,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	BrokenBolts ={
	type = "PZCrossbows.BrokenBolt",
		minCount=1,
		maxCount=3,
		xp=5,
		skill=4,
		categories = { "Junk" },
		zones = {
				BirchForest		= 5,
				PHForest		= 5,
				PRForest		= 5,
				DeepForest		= 5,
				FarmLand    	= 5,
				ForagingNav 	= 5,
				Forest      	= 5,
				OrganicForest	= 5,
				TownZone    	= 5,
				TrailerPark 	= 5,
				Vegitation  	= 5,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	BoltShaft ={
	type = "PZCrossbows.WoodBoltShaft",
		minCount=1,
		maxCount=5,
		xp=5,
		skill=4,
		categories = { "Junk" },
		zones = {
				BirchForest		= 1,
				PHForest		= 1,
				PRForest		= 1,
				DeepForest		= 1,
				FarmLand    	= 1,
				ForagingNav 	= 1,
				Forest      	= 1,
				OrganicForest	= 1,
				TownZone    	= 1,
				TrailerPark 	= 1,
				Vegitation  	= 1,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
	BoltHeads ={
	type = "PZCrossbows.StoneBoltHead",
		minCount=2,
		maxCount=8,
		xp=10,
		skill=4,
		categories = { "Junk" },
		zones = {
				BirchForest		= 1,
				PHForest		= 1,
				PRForest		= 1,
				DeepForest		= 1,
				FarmLand    	= 1,
				ForagingNav 	= 1,
				Forest      	= 1,
				OrganicForest	= 1,
				TownZone    	= 1,
				TrailerPark 	= 1,
				Vegitation  	= 1,
			},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	},
}

	-- The quiver can be found through foraging anywhere the hand crossbow can.
	-- Copy the zone table so scaling one definition never mutates the other.
	itemsToAdd.BoltQuiver = {
		type = "PZCrossbows.BoltQuiver",
		minCount = 1,
		maxCount = 1,
		xp = 10,
		skill = 4,
		categories = { "Junk" },
		zones = {},
		spawnFuncs = { doGenericItemSpawn },
		forceOutside = false,
		canBeAboveFloor = true,
	}
	for zoneName, weight in pairs(itemsToAdd.HandCrossbow.zones) do
		itemsToAdd.BoltQuiver.zones[zoneName] = weight
	end

	local vars = SandboxVars and SandboxVars.PZCrossbows
	local lootSpawnMult = (vars and vars.LootSpawnMult) or 1
	if lootSpawnMult < 0 then lootSpawnMult = 0 end

	local crudeMult = (vars and vars.CrudeCrossbowSpawnMult) or 1
	local improvedMult = (vars and vars.ImprovedCrossbowSpawnMult) or 1
	local compoundMult = (vars and vars.CompoundCrossbowSpawnMult) or 1
	local handMult = (vars and vars.HandCrossbowSpawnMult) or 1

	local itemMultipliers = {
		CompoundCrossbow = lootSpawnMult * compoundMult,
		ImprovedCrossbow = lootSpawnMult * improvedMult,
		CrudeCrossbow = lootSpawnMult * crudeMult,
		HandCrossbow = lootSpawnMult * handMult,
		ShortBolts = lootSpawnMult * handMult,
		ShortBrokenBolts = lootSpawnMult * handMult,
		ShortBoltShaft = lootSpawnMult * handMult,
		Bolts = lootSpawnMult * compoundMult,
		BrokenBolts = lootSpawnMult * compoundMult,
		BoltShaft = lootSpawnMult * compoundMult,
		BoltHeads = lootSpawnMult,
		BoltQuiver = lootSpawnMult,
	}

	for itemName, itemDef in pairs(itemsToAdd) do
		local multiplier = itemMultipliers[itemName] or lootSpawnMult
		if multiplier > 0 then
			for zoneName, weight in pairs(itemDef.zones) do
				itemDef.zones[zoneName] = weight * multiplier
			end
			forageSystem.addItemDef(itemDef)
		end
	end;
end);
